'''Autogenerated dummy select module anabling code completion in Python editors
 MODO Build #100509
'''

class AnySelection:
    def clear(self):
        '''Drop the selection without changing the selection mode.

        '''
        pass

    def drop(self):
        '''Drop the selection, changing the selection mode.

        '''
        pass

    def pkt_list(self):
        '''Return a list of raw selection packets.

        '''
        pass



class ChannelSelection:
    def __init__(self):
        self.selsvc = lx.service.Selection()
        self.spTrans = lx.object.ChannelPacketTranslation()
        self.stype = str()
        self.spType = long()

    def clear(self):
        '''Drop the selection without changing the selection mode.

        '''
        pass

    def current(self):
        '''Returns the currently selected channels as a list.
        Channels are given by an item / channel index pair.

        '''
        pass

    def drop(self):
        '''Drop the selection, changing the selection mode.

        '''
        pass

    def pkt_list(self):
        '''Return a list of raw selection packets.

        '''
        pass



class ItemSelection:
    def __init__(self):
        self.selsvc = lx.service.Selection()
        self.spTrans = lx.object.ItemPacketTranslation()
        self.stype = str()
        self.spType = long()

    def clear(self):
        '''Drop the selection without changing the selection mode.

        '''
        pass

    def current(self):
        '''Returns the currently selected items are returned as a list.

        '''
        pass

    def drop(self):
        '''Drop the selection, changing the selection mode.

        '''
        pass

    def pkt_list(self):
        '''Return a list of raw selection packets.

        '''
        pass

    def select(self, itemID, add):
        '''Select an item by ID or name

            itemID - name or ID of item to select
            add    - add to current selection or replace, default = replace

        '''
        pass



class PresetPathSelection:
    def __init__(self):
        self.selsvc = lx.service.Selection()
        self.spTrans = lx.object.PresetPathPacketTranslation()
        self.stype = str()
        self.spType = long()

    def clear(self):
        '''Drop the selection without changing the selection mode.

        '''
        pass

    def current(self):
        pass

    def drop(self):
        '''Drop the selection, changing the selection mode.

        '''
        pass

    def pkt_list(self):
        '''Return a list of raw selection packets.

        '''
        pass



class SceneSelection:
    def __init__(self):
        self.selsvc = lx.service.Selection()
        self.spTrans = lx.object.ScenePacketTranslation()
        self.stype = str()
        self.spType = long()

    def clear(self):
        '''Drop the selection without changing the selection mode.

        '''
        pass

    def current(self):
        '''Return the current scene.

        '''
        pass

    def drop(self):
        '''Drop the selection, changing the selection mode.

        '''
        pass

    def pkt_list(self):
        '''Return a list of raw selection packets.

        '''
        pass



