'''Autogenerated dummy vector module anabling code completion in Python editors
 MODO Build #100509
'''

def add(a, b):
    '''result = a + b'''
    pass

def cross(a, b):
    '''result = a x b'''
    pass

def dot(a, b):
    '''result = a . b'''
    pass

def length(v):
    '''result = sqrt (v . v)'''
    pass

def normalize(v):
    '''result = a / length(a)'''
    pass

def scale(v, s):
    '''result = v * s'''
    pass

def sub(a, b):
    '''result = a - b'''
    pass

def vector():
    '''Return a 3-vector (tuple of three values):
    Vector(x,y,z) = (x,y,z)
    Vector(a) = (a,a,a)
    Vector() = (0,0,0)

    '''
    pass

